export type SectionId = 1 | 2 | 3;
export type ExamQuestion = {
  id: string; section: SectionId; question: string; options?: string[]; correctAnswer: string; image?: string[];
};

// Answer keys stay in this server-only module. API responses are built with publicQuestion().
export const questions: ExamQuestion[] = [
  { id:"s1-01",section:1,question:"The STOPPIT-2 trial demonstrated the effectiveness of which intervention in preventing preterm labour in twins?",options:["Progesterone","Arabin cervical pessary","Cerclage","Antenatal corticosteroids"],correctAnswer:"Arabin cervical pessary" },
  { id:"s1-02",section:1,question:"Wells criteria is used for:",options:["Prediction of preeclampsia","Prediction of fetal congenital heart disease","Thromboembolic risk assessment","Disseminated intravascular coagulation risk assessment"],correctAnswer:"Thromboembolic risk assessment" },
  { id:"s1-03",section:1,question:"A 30-year-old G2A1 with BMI 30 kg/m², known PCOS, conceived on IUI and presents at 18 weeks. Her gestosis score is:",options:["0","1","2","3"],correctAnswer:"1" },
  { id:"s1-04",section:1,question:"A 20-year-old primigravida at 36 weeks presents with nausea, vomiting, malaise, jaundice and abdominal pain. BP is 150/100 mmHg, platelets 95,000, AST/ALT 180/150 IU/L, moderately elevated LDH, glucose 48 mg/dL and urine protein 1+. Acute fatty liver of pregnancy can be differentiated from HELLP syndrome by the presence of:",options:["Hypertension","Jaundice","Low blood sugar","Coagulopathy"],correctAnswer:"Low blood sugar" },
  { id:"s1-05",section:1,question:"As per NACO, which colour-coded kit is given for a 40-year-old woman with genital herpes?",options:["Yellow","Green","Red","Blue"],correctAnswer:"Red" },
  { id:"s1-06",section:1,question:"After hysteroscopic resection of a submucous fibroid using glycine, a patient develops confusion, nausea, vomiting and headache. The diagnosis is:",options:["Glycine toxicity","Uterine perforation","Pulmonary oedema","Hyponatremic hypervolemia"],correctAnswer:"Hyponatremic hypervolemia" },
  { id:"s1-07",section:1,question:"During labour epidural analgesia, a woman develops perioral numbness, hypotension and generalized tonic-clonic seizures, remaining hypotensive despite airway management and seizure control. What is the specific antidotal treatment?",options:["20% lipid emulsion","Calcium gluconate","Sodium bicarbonate","Immediate cardioversion"],correctAnswer:"20% lipid emulsion" },
  { id:"s1-08",section:1,question:"Which ovarian malignancy has the strongest established epidemiological association with endometriosis?",options:["Serous carcinoma","Mucinous carcinoma","Brenner carcinoma","Clear cell carcinoma"],correctAnswer:"Clear cell carcinoma" },
  { id:"s1-09",section:1,question:"Who is the father of Indian gynaecology?",options:["B.N. Purandare","Sir Kedarnath Das","S.B. Anklesaria","H.M. Lazarus"],correctAnswer:"B.N. Purandare" },
  { id:"s1-10",section:1,question:"Which Doppler vessel provides information about central venous/cardiac function and may show abnormality before overt fetal heart failure in severe early FGR?",options:["Umbilical artery","Middle cerebral artery","Ductus venosus","Umbilical vein"],correctAnswer:"Ductus venosus" },
  { id:"s1-11",section:1,question:"ReCoDe classification is for:",options:["Stillbirth","Maternal mortality","Maternal near miss","Caesarean audit"],correctAnswer:"Stillbirth" },
  { id:"s1-12",section:1,question:"A woman with rheumatoid arthritis is found to be 6 weeks pregnant. Which drug is associated with teratogenicity and should be avoided?",options:["Azathioprine","Mycophenolate mofetil","Sulfasalazine","Hydroxychloroquine"],correctAnswer:"Mycophenolate mofetil" },
  { id:"s1-13",section:1,question:"A woman had unprotected intercourse last night and had a vaginal delivery 2 weeks ago. She asks for emergency contraception. Which is the most suitable option?",options:["IUCD","LNG IUS","Ulipristal acetate","No need for any contraceptive"],correctAnswer:"No need for any contraceptive" },
  { id:"s1-14",section:1,question:"What percentage of dermoid cysts undergo malignant transformation?",options:["5%","2%","10%","20%"],correctAnswer:"2%" },
  { id:"s1-15",section:1,question:"Partial cul-de-sac obliteration in endometriosis gives which score in the revised ASRM classification?",options:["4","1","3","5"],correctAnswer:"4" },
  { id:"s1-16",section:1,question:"The advantage of docetaxel over paclitaxel in chemotherapy of ovarian malignancy is:",options:["Less haematotoxicity","Less nausea and vomiting","Fewer neurological effects and less arthralgia","Less alopecia"],correctAnswer:"Fewer neurological effects and less arthralgia" },
  { id:"s1-17",section:1,question:"In a man with azoospermia, which Y-chromosome microdeletion is associated with virtually no chance of retrieving sperm by conventional TESE?",options:["AZFc deletion","AZFa deletion","Isolated AZFc duplication","Partial AZFc deletion only"],correctAnswer:"AZFa deletion" },
  { id:"s1-18",section:1,question:"First-line topical treatment for vulvar lichen sclerosus is:",options:["Ultrapotent topical corticosteroid","Topical estrogen cream","Topical 5-fluorouracil","Oral antihistamines only"],correctAnswer:"Ultrapotent topical corticosteroid" },
  { id:"s1-19",section:1,question:"Which endometrial cancer molecular subtype has the best prognosis?",options:["POLE-ultramutated","Microsatellite instability-high (MSI-H)","Copy-number high / p53-abnormal (serous-like)","Copy-number low / no specific molecular profile (NSMP)"],correctAnswer:"POLE-ultramutated" },
  { id:"s1-20",section:1,question:"Clear cell adenocarcinoma of the vagina/cervix in young women has historically been linked to in-utero exposure to which agent?",options:["Thalidomide","Diethylstilbestrol (DES)","Valproic acid","Isotretinoin"],correctAnswer:"Diethylstilbestrol (DES)" },
  { id:"s2-01",section:2,question:"The chromosomal aneuploidy which manifests with significant fetal growth restriction is ______.",correctAnswer:"Trisomy 18"},
  { id:"s2-02",section:2,question:"Counselling for X-ray exposure from a single diagnostic procedure in a pregnant woman involving less than ______ rads has no fetal detrimental effects.",correctAnswer:"5"},
  { id:"s2-03",section:2,question:"The most common organism that causes severe sepsis syndrome in obstetrics is ______.",correctAnswer:"E. coli"},
  { id:"s2-04",section:2,question:"The symbol shown in the pedigree chart represents ______.",correctAnswer:"Dizygotic twinning",image:["/exam/image1.png"]},
  { id:"s2-05",section:2,question:"A genital infection which could cause ectopic pregnancy is ______.",correctAnswer:"Chlamydia trachomatis"},
  { id:"s2-06",section:2,question:"Increasing pain several days after medical management of ectopic pregnancy is due to ______.",correctAnswer:"Separation pain"},
  { id:"s2-07",section:2,question:"FETO (acronym) is a fetoscopic procedure done for ______.",correctAnswer:"Congenital diaphragmatic hernia (CDH)"},
  { id:"s2-08",section:2,question:"The CTG pattern with an acceleration followed by a variable deceleration, with no acceleration at the end of the deceleration, is called ______.",correctAnswer:"Lambda"},
  { id:"s2-09",section:2,question:"A complication a fetus may develop because of hypercoiling of the cord is ______.",correctAnswer:"FGR, acidosis, asphyxia"},
  { id:"s2-10",section:2,question:"A pelvic umbrella pack in obstetrics is used for ______.",correctAnswer:"Continued bleeding after hysterectomy for PPH"},
  { id:"s2-11",section:2,question:"The dilution used for vasopressin for hydrodissection in myomectomy is ______.",correctAnswer:"20 units in 200 ml"},
  { id:"s2-12",section:2,question:"The best available tool to classify endometriosis is ______.",correctAnswer:"ASRM revised classification"},
  { id:"s2-13",section:2,question:"The catheterization period for injury to the trigone of the bladder is ______.",correctAnswer:"10–14 days"},
  { id:"s2-14",section:2,question:"The urodynamic measure of the minimum intra-abdominal or intravesical pressure required to cause incontinence during abdominal strain or cough is called ______.",correctAnswer:"Leak point pressure"},
  { id:"s2-15",section:2,question:"The initial drug of choice to treat overactive bladder is ______.",correctAnswer:"Oxybutynin"},
  { id:"s2-16",section:2,question:"The serious cardiovascular risk in a patient with Turner syndrome is ______.",correctAnswer:"Aortic dissection"},
  { id:"s2-17",section:2,question:"The phenotypic differentiating factor between 5-alpha-reductase deficiency and TFS is ______.",correctAnswer:"No breast development"},
  { id:"s2-18",section:2,question:"The best diagnostic modality for endometrial polyps is ______.",correctAnswer:"SIS (Saline Infusion Sonography)"},
  { id:"s2-19",section:2,question:"The medial and lateral borders of Okabayashi space are ______.",correctAnswer:"Rectum and ureter"},
  { id:"s2-20",section:2,question:"On ultrasound, polycystic ovarian morphology in an adult is defined in the 2023 international guideline as ______ follicles per ovary.",correctAnswer:"More than or equal to 20"},
  { id:"s3-01",section:3,question:"A 26-year-old G2P1 presents for an anomaly scan at 20 weeks. The fetal head shows frontal bone scalloping and the cerebellum appears curved anteriorly. What is the most likely diagnosis?",options:["Dandy-Walker malformation","Aqueductal stenosis","Open spina bifida with Arnold-Chiari II malformation","Holoprosencephaly","Agenesis of corpus callosum"],correctAnswer:"Open spina bifida with Arnold-Chiari II malformation",image:["/exam/image2.webp","/exam/image3.jpeg"]},
  { id:"s3-02",section:3,question:"A 29-year-old primigravida at 29+4 weeks has severe early-onset FGR, with estimated fetal weight below the 3rd centile. Umbilical artery Doppler images are shown. What is the most appropriate next step?",options:["Repeat scan after one week","Oral aspirin therapy","Continue expectant management until 34 weeks","Immediate delivery after corticosteroids and magnesium sulphate","Perform amniocentesis"],correctAnswer:"Immediate delivery after corticosteroids and magnesium sulphate",image:["/exam/image4.png"]},
  { id:"s3-03",section:3,question:"A 31-year-old with three first-trimester miscarriages undergoes 3D transvaginal ultrasound. The coronal plane shows a normal external fundal contour with an internal fundal indentation extending >15 mm into the cavity. What is the diagnosis?",options:["Septate uterus","Arcuate uterus","Bicornuate uterus","Didelphys uterus","Unicornuate uterus"],correctAnswer:"Septate uterus",image:["/exam/image5.png"]},
  { id:"s3-04",section:3,question:"A 48-year-old presents with postcoital bleeding. MRI demonstrates a 4.5 cm cervical lesion extending into the parametrium without pelvic sidewall involvement. What is the FIGO 2018 stage?",options:["IB3","IIA2","IIB","IIIA","IIIC1"],correctAnswer:"IIB",image:["/exam/image6.jpeg","/exam/image7.jpeg"]},
  { id:"s3-05",section:3,question:"A 32-year-old on postoperative day 2 after LSCS develops sudden dyspnoea, tachycardia and oxygen saturation of 84%. CTPA shows the image. What is the most appropriate management?",options:["Systemic thrombolysis","Therapeutic LMWH alone","Low-dose aspirin","IVC filter only","Repeat CTPA after 48 hours"],correctAnswer:"Systemic thrombolysis",image:["/exam/image8.jpeg"]},
  { id:"s3-06",section:3,question:"During diagnostic laparoscopy, identify the marked structure.",options:["Inferior epigastric artery","Median umbilical ligament","Medial umbilical ligaments","Round ligament","Lateral umbilical ligaments"],correctAnswer:"Medial umbilical ligaments",image:["/exam/image9.jpeg"]},
  { id:"s3-07",section:3,question:"A 51-year-old smoker develops cough, fever, tachycardia and breathing difficulty after total abdominal hysterectomy with bilateral salpingo-oophorectomy. The chest radiograph is shown. What is the most likely diagnosis?",options:["Pneumonia","Atelectasis","Tuberculosis","Lung cancer","Pleural effusion"],correctAnswer:"Atelectasis",image:["/exam/image10.jpeg"]},
  { id:"s3-08",section:3,question:"Interpret the POP-Q grid. What is the diagnosis?",options:["Posterior vaginal wall prolapse","Apical prolapse","Apical prolapse with posterior vaginal wall prolapse","Cystocele","Cystocele with urethrocele"],correctAnswer:"Posterior vaginal wall prolapse",image:["/exam/image11.png"]},
  { id:"s3-09",section:3,question:"A woman with recurrent miscarriages and a uterine septum undergoes septal resection using the instrument shown. What type of distension medium is recommended?",options:["Hypotonic sorbitol 3%","Hypotonic sorbitol 1.5%","Hypotonic glycine 1.5%","Isotonic glycine","Isotonic normal saline"],correctAnswer:"Isotonic normal saline",image:["/exam/image12.jpeg","/exam/image13.jpeg"]},
  { id:"s3-10",section:3,question:"A 50-year-old diabetic is planned for laparoscopic-assisted vaginal hysterectomy with bilateral salpingo-oophorectomy. All of the following enhanced recovery measures should be followed except:",options:["Pre-operative planning of the day of discharge","Pre-operative patient education to reduce the need for pain relief","Avoid dehydration by reducing fasting; allow clear fluids until the appropriate pre-anaesthetic interval","Use of complex carbohydrate drinks reduces pre-operative thirst, hunger and post-operative insulin resistance","Avoid mechanical bowel preparation, which is unpleasant and has no evidence of improved outcomes"],correctAnswer:"Use of complex carbohydrate drinks reduces pre-operative thirst, hunger and post-operative insulin resistance",image:["/exam/image14.png"]}
];

export const sectionInfo = [
  { id: 1 as const, title: "Multiple Choice Questions", shortTitle: "Section 1", count: 20, durationSeconds: 20 * 60 },
  { id: 2 as const, title: "One Word / One Sentence", shortTitle: "Section 2", count: 20, durationSeconds: 20 * 60 },
  { id: 3 as const, title: "Image-Based Questions", shortTitle: "Section 3", count: 10, durationSeconds: 10 * 60 }
];

export function publicQuestion(q: ExamQuestion) {
  const { correctAnswer: _secret, ...safe } = q;
  return safe;
}
